"""Anti-tamper check for the autoscoring pipeline.

The rule: a submission may only ADD new files under
`submissions/<their-name>/`. Every file that existed anywhere in the repo
at release time - scoring/, every use case's tests/ and
scoring_hooks.py, benchmark/, workflow files, docs, READMEs, and yes,
submissions/README.md too - is hashed into
scoring/PROTECTED_MANIFEST.json (generated by
scripts/generate_protected_manifest.py). This module recomputes those
hashes against the checked-out tree and fails closed on:

  - any protected file that was changed
  - any protected file that was deleted
  - any new file created OUTSIDE submissions/ that wasn't already tracked

A new file created INSIDE submissions/ is fine - that's just a participant
adding their own work.

CI runs this as the very first step, before installing dependencies or
running any scoring - a tampered PR never reaches the scoring engine at
all, so there's no code path where editing scoring/tests/workflow files
could raise a score.

Known limitation: this defends the *files* the scoring pipeline reads. It
does not, and cannot fully, defend against a PR that edits
`.github/workflows/**` and relies on GitHub running that PR's own copy of
the workflow for a `pull_request` trigger - GitHub's own mitigation for
that is requiring approval to run workflows from outside/first-time
contributors. See docs/HIRING_GUIDE.md - that repository setting is a
required part of this design, not optional.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

IGNORE_DIR_NAMES = {
    ".git", "__pycache__", ".venv", "venv", ".pytest_cache", ".ruff_cache",
    ".score", "score-output", "node_modules", ".mypy_cache",
}
IGNORE_FILE_SUFFIXES = {".pyc"}
# No data files are generated at runtime in the current use cases — all
# data is committed and should be protected. If a future use case adds a
# data/generate_data.py that produces uncommitted files, add its prefix
# here with IGNORE_SUFFIXES_UNDER_PREFIX to skip those from the manifest.
IGNORE_RELATIVE_PREFIXES: tuple[str, ...] = ()
IGNORE_SUFFIXES_UNDER_PREFIX = {".csv", ".json"}
MANIFEST_RELATIVE_PATH = "scoring/PROTECTED_MANIFEST.json"


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _iter_protected_files(repo_root: Path):
    for path in sorted(repo_root.rglob("*")):
        if path.is_dir():
            continue
        if any(part in IGNORE_DIR_NAMES for part in path.parts):
            continue
        if path.suffix in IGNORE_FILE_SUFFIXES:
            continue
        rel = path.relative_to(repo_root)
        rel_posix = rel.as_posix()
        if rel_posix == MANIFEST_RELATIVE_PATH:
            continue
        if rel_posix.startswith(IGNORE_RELATIVE_PREFIXES) and rel.suffix in IGNORE_SUFFIXES_UNDER_PREFIX:
            continue
        yield rel


def build_manifest(repo_root: Path) -> dict:
    # .as_posix() is required, not cosmetic: this manifest is generated on
    # whatever OS the challenge author is using (Windows included) but
    # always verified in Linux CI - str(rel) would emit backslash-joined
    # keys on Windows that would never match a POSIX rebuild.
    return {rel.as_posix(): _sha256(repo_root / rel) for rel in _iter_protected_files(repo_root)}


def check_integrity(repo_root: Path, manifest_path: Path, expected_manifest_sha256: str | None = None) -> tuple[bool, str]:
    if not manifest_path.is_file():
        return False, f"Protected manifest not found at {manifest_path} - cannot verify integrity."

    if expected_manifest_sha256:
        actual = _sha256(manifest_path)
        if actual != expected_manifest_sha256:
            return False, (
                "scoring/PROTECTED_MANIFEST.json itself does not match the expected hash "
                f"(expected {expected_manifest_sha256}, got {actual}) - PR disqualified.\n\n"
                "The expected hash is checked against the PROTECTED_MANIFEST_SHA256 "
                "repository variable, which lives in repo Settings, outside anything a "
                "PR can touch."
            )

    manifest = json.loads(manifest_path.read_text())
    current = build_manifest(repo_root)

    changed, deleted = [], []
    for rel, expected_hash in manifest.items():
        actual_hash = current.get(rel)
        if actual_hash is None:
            deleted.append(rel)
        elif actual_hash != expected_hash:
            changed.append(rel)

    all_new_files = set(current) - set(manifest)
    new_outside_submissions = sorted(f for f in all_new_files if not f.startswith("submissions/"))

    if not changed and not deleted and not new_outside_submissions:
        return True, f"Integrity OK - {len(manifest)} protected file(s) unchanged."

    lines = ["Protected files were modified - PR disqualified.", ""]
    if changed:
        lines.append(f"Changed ({len(changed)}): " + ", ".join(changed))
    if deleted:
        lines.append(f"Deleted ({len(deleted)}): " + ", ".join(deleted))
    if new_outside_submissions:
        lines.append(f"New file(s) outside submissions/ ({len(new_outside_submissions)}): "
                      + ", ".join(new_outside_submissions))
    lines += [
        "",
        "Only NEW files under submissions/<your-name>/ are allowed. If you believe one "
        "of these files needs a genuine fix, say so in your PR description instead of "
        "editing it directly.",
    ]
    return False, "\n".join(lines)


def main() -> int:
    import argparse
    import os

    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--manifest", default=None)
    parser.add_argument("--manifest-sha256", default=None,
                         help="Defaults to the PROTECTED_MANIFEST_SHA256 env var.")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    manifest_path = Path(args.manifest) if args.manifest else repo_root / "scoring" / "PROTECTED_MANIFEST.json"
    expected_sha256 = args.manifest_sha256 or os.environ.get("PROTECTED_MANIFEST_SHA256")

    ok, message = check_integrity(repo_root, manifest_path, expected_sha256)
    print(message)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
